# Generated by Django 4.2.5 on 2023-09-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_about', models.CharField(max_length=80)),
                ('blog_detail', models.CharField(max_length=2000)),
                ('blog_img', models.ImageField(default='def.png', upload_to='pic')),
            ],
        ),
    ]
